### ISSUE TITLE
Short algorithm tweak

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#1020]
Average score of well performing shorts are at 4, if an addition of 4 is added as recency boost, it would only show recently published shorts basically for the first 4-5 days.

Noticed there is a disadvantage of having this, we create shorts in batches from a same assets. Within 10 new shorts, 3-4 shorts are from same film, which could seem very repetitive if they show up as first 10 shorts.

-----
## Agreed solution

Implement a filter that ensures that shorts linked to the same episode are at least 5 shorts apart.
This can be implemented by discarding shorts linked to the same episode in a sliding window.

**Comment by KillerX** [comment]
To be reviewed: #1026

**Comment by mulundapm** [comment]
I just published 16 shorts and it takes 15 swipe before i get 1 short from that batch

**Comment by KillerX** [comment]
You have a local queue that is respected 1st. Also the scores are synced nightly, so when did you upload them?
