### ISSUE TITLE
User interview for BCCM (Shorts and non-norwegian speakers)

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#1052]
- [x] #1055
- [x] #1053
- [x] Scheduling web (calendly? microsoft? cal.com)
- [x] #1054

[Design](https://www.figma.com/design/BMXWzaA93qm8jXKjyPiFOs/BCC-Media-%E2%80%93-Mobile-App-V4?node-id=11-27443&node-type=canvas&t=McdL5LMcDpR2bgue-0)

![Image](https://github.com/user-attachments/assets/825bcf61-301d-4b0f-8c4b-9d1b36feceb5)

**Comment by sifferhans** [comment]
@mulundapm My part here is done
