### ISSUE TITLE
Backend to add "Link" as question type in survey

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#1053]

**Comment by sifferhans** [comment]
@KillerX Looks good 👍 the `cancelButtonText` can be optional though, as we discussed

**Comment by KillerX** [comment]
You can take a look at https://github.com/bcc-code/bcc-media-platform/pull/1061
It's still in draft as I had to jump over to the other urgent things and have done 0 testing, but let me know if you see some issues.

**Comment by KillerX** [comment]
@sifferhans the UX test survey should have this type of question now.
