### ISSUE TITLE
Frontend for user interview: Button to open link in survey

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#1055]

**Comment by sifferhans** [comment]
This is another (better imo) layout

![Image](https://github.com/user-attachments/assets/53d40f01-bd05-4fd5-8918-7ffa40e784fa)

**Comment by mulundapm** [comment]
Why is the second one better? 

Kinda like the first one since the button takes less space, looks cleaner. But with the number of character we will have there, not sure it would look equally good on narrow phones.

**Comment by sifferhans** [comment]
## Examples of the full-width button pattern:

![Image](https://github.com/user-attachments/assets/f4fc5536-95a1-4e13-8dcd-dc404b63b0f6)

![Image](https://github.com/user-attachments/assets/929ae497-6d78-4dbe-82e7-6dafba1f283f)

![Image](https://github.com/user-attachments/assets/d0ffdc67-ae25-4f37-969d-789aec54039f)

**Comment by sifferhans** [comment]
I do, however, see that the designer specifically designed the survey buttons like this
![Image](https://github.com/user-attachments/assets/c8abbaa9-32fb-4da3-a6a2-98c50d7394b7)

**Comment by sifferhans** [comment]
I am blocked from publishing a new version, as the test runner we use in CI is crashing. I'll need to fix that before this is testable

**Comment by sifferhans** [comment]
This is now in TestFlight
