### ISSUE TITLE
BCCM health dashboard

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#1066]
- [x] Export playback errors from npaw to metabase
- [x] Create Dashboard(s)
- [x] Make sure they are finadable and available to the team

A dashboard that gives insight on general issues
e.g. reference to bmm dashboard

**Comment by KillerX** [comment]
Addition from Metabase here: https://metabase.bcc.media/dashboard/57-bccm-platfrom-errors-db

**Comment by KillerX** [comment]
Central page: https://www.notion.so/bccmedia/Stream-Troubleshooting-14a563c0cccf800e9e57ed14d1153247
Linked from: https://www.notion.so/bccmedia/a71370072a2e4ea98af9df4eb6eac098?v=9c8c864a49b44619a530fd6556605c2f

**Comment by KillerX** [comment]
@kkuepper @sifferhans can you guys confirm that you have access to the links in: https://www.notion.so/bccmedia/Stream-Troubleshooting-14a563c0cccf800e9e57ed14d1153247

NPAW, Metabase, AWS

**Comment by sifferhans** [comment]
I don't have AWS login. Matjaz will help me set it up
