### ISSUE TITLE
Downloadables

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-platform#321]
Status:

Import mostly works.
URLs in API work.

ToDo:

- [x] Store the file size when importing
- [x] Store language, subtitle language
- [x] Get the file resolution and store it (This may need cooperation with Mediabanken)

**Comment by andreasgan** [comment]
just throwing an idea on the resolution: I think ffprobe only downloads the necessary bytes if you use it on a remote url.
but ofc, you shouldn't do that unless it significantly simplifies stuff...
https://aws.amazon.com/blogs/media/analyzing-media-files-using-ffprobe-in-aws-lambda/
https://superuser.com/questions/541001/does-ffprobe-download-the-file

**Comment by KillerX** [comment]
It's an option but considering Mediabanken is delivering that file it should be trivial to include the data when submitting the file for import.
