### ISSUE TITLE
Create new fields for episode content type and add to metabase

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#323]
**User story**
As an analyst, I want to be able to filter VOD based on content type and audience, so that do analysis on specific types of VOD in metabase.

**Description**
New fields to be added in direct us

Type:
- Other transmission
- Event transmission
- Individual film
- Series film

Audience:
- Kids
- Youth
- General

**Acceptance criteria**
1. Able to admin types/ audience in directus on episode level
2. Types and audience is available in rudderstack_prod.episodes in metabase

**Comment by KillerX** [comment]
Nature?? Sorry but I have no clue what you are referring to :D

**Comment by mulundapm** [comment]
Back to type it is.

**Comment by andreasgan** [comment]
can just use tags instead of "type" for this

**Comment by KillerX** [comment]
@fredrikved can you add this to the DB, and let me know. I'll update the BQ sync after

**Comment by fredrikved** [comment]
> can just use tags instead of "type" for this

Tags could be used for this, but guessing thats not enough or?
@KillerX @mulundapm

**Comment by fredrikved** [comment]
Fields should be added. Ready to sync to BQ @KillerX
