### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#327]
**Use story** 
1. As a user, I want to be able to navigate to FAQ, so that I am able to find if my inquiry could be answered
2. As an admin, I want to be able to update FAQ anytime and group questions

**Acceptance criteria**
1. Have FAQ in the same grouping as contact support in profile page
2. Grouping of questions from admin so user are able to navigate based on context set by admin
3. Translation

[Figma design](https://www.figma.com/file/BMXWzaA93qm8jXKjyPiFOs/BCC-Media-%E2%80%93-Mobile-App-V4?node-id=0%3A1199&t=m5T6EAvQ6lmdOZPP-1)

- [x] backend (#332)
- [x] web
- [x] app (https://github.com/bcc-code/bcc-media-app/pull/159)
- [x] Translation

**Comment by andreasgangso** [comment]
only missing web

**Comment by mulundapm** [comment]
Faq will have to be included in crowdin @fredrikved

**Comment by mulundapm** [comment]
It now is

**Comment by mulundapm** [comment]
If category is empty, then will have to hide category. 

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/813e5831-f7ac-4af8-9e43-886ef5f5ff4a)

**Comment by fredrikved** [comment]
Also a permissions thing. Will be based on Question visibility as well.
