### ISSUE TITLE
Playback- request new urls upon expiry

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#329]
There are a lot of errors from expired tokens in NPAW and it makes it sort of useless for debugging for that reason.

https://teams.microsoft.com/l/message/19:020351fd083f4e66bcf0b4e5555a3d94@thread.tacv2/1683203117214?tenantId=8572f54e-d0a8-4ea4-a28e-557c63698a4a&groupId=65a25340-a2b5-4933-873d-dec0f984fc5a&parentMessageId=1683203117214&teamName=BCC%20Media%20-%20Redaksjon&channelName=BCCM%20app%20web&createdTime=1683203117214&allowXTenantAccess=false

**Comment by andreasgangso** [comment]
We verified now that ~95% of these errors are from the old AppleTV app.
So we are not going to prioritize this for the mobile apps.
We'll monitor if the new appletv app has the same issues and fix it if it does.
