### ISSUE TITLE
Autoplay next

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#330]
**User story**
1. As a parent, when I start a video within a playlist, I want to episodes to play automatically so my child doesn't need my assistance to start the next video

**Acceptance criteria**
1. An indicator to inform users next video will start playing soon
3. Preview of next episode's episode title and episode thumbnail
4. The next video should start in the same state as current video, except when video is in Pip
5. Same language setting as current video

**Comment by andreasgan** [comment]
If this is only for the app it should be written somewhere, and it should be moved to the app repository.
if its for web too then its ok that it's here, but then fredrik should be assigned too

**Comment by andreasgan** [comment]
@mulundapm

**Comment by KillerX** [comment]
> Backend control is not a part of the acceptance criteria here

To clarify: My thoughts are backend control of "what" not the actual playback

**Comment by andreasgangso** [comment]
From my side it would be nice to have the backend ready here within a few days if possible @fredrikved @mulundapm 
Need e.g. a field on the episode signalling which episode to play after this one.

**Comment by andreasgangso** [comment]
It can be simple for the first iteration; the next episode in the context

**Comment by mulundapm** [comment]
@andreasgangso Sorry only read this now, it should be on both. @fredrikved Are you able to prioritise this this week?

**Comment by andreasgangso** [comment]
> I think it would make sense to have it as an array, even if we for now just use 1. Feels like little extra work for potentially reduced hassle down the line should we want more than one.
> 
> Potential use cases:
> 
> Kids: Show several options, auto pick next but allow picking any Speech: Deep dive into one of multiple themes ...

If it's no practical difference in the backend thats ok with me.
The field should be called "nextUp" or something then.
But i doubt this will be useful because if we are going to show choices to the user it's not necessarily the same as what we would automatically select for autoplay.

**Comment by fredrikved** [comment]
#354

**Comment by mulundapm** [comment]
https://github.com/bcc-code/bcc-media-platform/assets/88234679/b5b59ffb-e812-40e0-b08f-96cb000aead5

Hi, tested with latest kips app and had these 2 issue

1. Video quit playing state when scroll towards the end of video
2. Auto playnext doesnt happen

**Comment by andreasgangso** [comment]
@mulundapm autoplay next was behind a feature flag. Works now, but it's enabled for the bcc media app (beta) too. will fix that before releasing bcc media.

1. needs to be fixed but i wouldn't halt the initial release to wait for a fix
