### ISSUE TITLE
Application groups

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#344]
**Problem**
When we have multiple apps, we don't want to share profiles between them (e.g. my-list, continue watching, etc).

We have "applications" and we could split profiles per application.
The problem is that it has fields like "client version", "frontpage", "searchpage", etc. which we may want to distuingish between platforms (web, mobile, and tv). So we would end up with split profiles between platforms.

**Proposed solution**
Introduce Application Groups, example:
- Application Group: bccm
  - Child Applications: bccm-mobile, bccm-tvos, bccm-web
- Application group: kids
  - Child applications: kids-mobile, kids-web
 
We would then split profiles and usergroups per application group, while allowing us to customize frontpage etc per platform.

**Comment by andreasgan** [comment]
@KillerX

**Comment by KillerX** [comment]
Why do we not want to share profiles?

**Comment by andreasgan** [comment]
> Why do we not want to share profiles?

We want to split bcc media users from biblekids users because there are likely different "profiles" using them.
But we need to keep in mind that in the future we may want to share profiles across groups. So maybe make profiles<->appgroups many-to-many

**Comment by KillerX** [comment]
Should only the pages be per application or also the content?
