### ISSUE TITLE
Redirect brunstad.tv to app.bcc.media

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#371]

**Comment by andreasgangso** [comment]
Remember to put stuff to "to be tested" @fredrikved 
This doesnt seem to work

**Comment by fredrikved** [comment]
Had to revert the change actually

**Comment by KillerX** [comment]
To verify before change:

* [ ] Is africa using any aspect?
* [ ] Is AppleTV updated enough that we can disable the old API
   * I think we still need to wait at this point  ![Image](https://github.com/bcc-code/bcc-media-platform/assets/398737/9664a80e-0abb-42f5-a0e3-8d3dd70024c5)
* [ ] Embedded videos and Kids explorers need to use the new API

**Comment by mulundapm** [comment]
Thats 20%, quite a lot but best to do it earlier than closer to the conference right? So users have time to adopt?

**Comment by KillerX** [comment]
It will be pretty transparent for users. I think biggest issue is Explorers downloadables.

**Comment by KillerX** [comment]
@mulundapm I think it's good to go then if you are ok with breaking the 3.x.x series of TvOS releases.
