### ISSUE TITLE
Download offline content (UI and removal logic)

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#374]
As a logged in user I want to download content to my mobile device, so that I can watch content offline

A pop-up for user to select language and quality when download is clicked. By default, select previously input value. If previous selected language is not available on current episode, show clear feedback to user that it is not available and that they could not click confirm to download until another available language is selected.

Acceptance criteria:
1. Do not sync download across platforms
2. Feature only available on mobile apps
4. Offline content should be removed if user is not online within 7 days
5. Offline content should be removed when it reaches its "Available to" date or when asset is no longer published
6. Offline content should be removed after 30 days regardless of online states
7. Feature only available for logged in users
8. Offline mode in app (Show users they are in offline mode on home page, search page and live page)

Remaining:
- [x] - Remember choices
- [x] - Error if language selection is not available
- [x] - Availability/ deletion policies
- [x] - UI polish
- [x] - Warning for not enough available space
- [x] - Permission prompt
- [x] analytics

**Comment by mulundapm** [comment]
How should language and quality be handled or selected? Download all by default? Is it feasible?

**Comment by andreasgangso** [comment]
> How should language and quality be handled or selected? Download all by default? Is it feasible?

Right now the planned implementation is to use the simple progressive mp4s with only 1 audio track. Subtitles will be on the side, if at all.
They have to select a language. For quality I'd suggest to have 1080p as default and make it configurable in settings somewhere for those who really need to configure that.
Needs some ux work.

**Comment by mulundapm** [comment]
What do you think of this

A pop-up when user is downloading for the first time, to select language and audio. 
Then have 2 selections to either "Save for future downloads" or "Just this time"
If they select save for future download, they can adjust them later in setting if wanted
If they select "Just this time", then this would pop up again next time

**Comment by mulundapm** [comment]
Then will do it as you mentioned, a pop-up that saves previous input on every download.

**Comment by mulundapm** [comment]
But then the download list would have to show all languages and clear to user which is not available on this episode

**Comment by andreasgangso** [comment]
another ux issue: mobile data warning

**Comment by mulundapm** [comment]
Its important to include analytics as well

**Comment by andreasgangso** [comment]
Suggestion: Show the expired downloads as "expired" instead of removing them.
I believe the way it works now can be frustrating, especially when it comes to availability. If the item for whatever reason is no longer published / you no longer have access, the download will just disappear with no trace of it.

**Comment by andreasgangso** [comment]
**Analytics**
Anything I missed?

- download_started
  - downloadId (unique per download, can be used to track a particular download across the events)
  - episodeId
  - quality (low, medium, high)
  - audioLanguage
- download_removed
  - downloadId
  - episodeId
- download_played
  - downloadId
  - episodeId

**Comment by mulundapm** [comment]
Will have to include the play events in npaw if thats possible but that can come later

**Comment by andreasgangso** [comment]
> Will have to include the play events in npaw if thats possible but that can come later

It should appear in npaw

**Comment by mulundapm** [comment]
Hi, iOS crashes when downloading standalones

**Comment by mulundapm** [comment]
Download failed, think its because of device is full. But I got the error message about storage full after I left the app. (a pop up saying storage full when im in another app right after using bcc media app) and when I navigate back to the app, the app crashes
https://github.com/bcc-code/bcc-media-platform/assets/88234679/80188a48-4ce6-4288-ab2f-e596b71e17e5

**Comment by andreasgangso** [comment]
I dont understand what you mean by "A pop up saying storage full when im in another app right after using bcc media app and when I navigate back to the app, the app crashes"

**Comment by andreasgangso** [comment]
v4.9.4 has these fixes: https://github.com/bcc-code/bcc-media-platform/issues/374#issuecomment-1734963705

**Comment by andreasgangso** [comment]
Actually, I'm unsure if I really fixed the force close thing but it's an attempt.

**Comment by mulundapm** [comment]
Im not sure how i could reproduce it but now I cant download files, it either set in queue for a long time or shows 100% downloadabled but doesnt play the offline version. Force closes or uninstall the app doesnt help. 

Before uninstall: https://github.com/bcc-code/bcc-media-platform/assets/88234679/31f5c0f4-351b-4bf5-97b2-edea3a71a33d

![Attempt after re-install](https://github.com/bcc-code/bcc-media-platform/assets/88234679/c85bccbf-27d6-4781-ac69-11a7585169a1)

**Comment by mulundapm** [comment]
Was able to reproduce this on test device. But unlike my device, this is not reproducible after reinstalling. 

1. Download offline file from previous version (there were 5 downloaded asset and 1 failed asset)
2. Update app to latest version
3. Remove all previously downloaded assets
4. Download new assets
5. Shows 100% downloaded without being able to play the offline version
