### ISSUE TITLE
Move Bible Kids, BCC Media and BMM to "BCC Media STI" app store account

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#379]
Same account that host BibleX mobile app

**Comment by mulundapm** [comment]
Hi Matjaz, got feedback from Kjetil that instead of changing to bcc.media foundation, we should create one called BCC Media STI and move BibleX, BMM, BibleKids and BCC Media over.

**Comment by KillerX** [comment]
> Your enrollment is being processed.
> 
> Enrollment ID: <REMOVED>
> 
> Once we verify your authority to sign legal agreements, we'll email you with instructions on how to complete your enrollment.
>

**Comment by KillerX** [comment]
Waiting for Apple and Google

**Comment by KillerX** [comment]
Google part is finished: https://play.google.com/store/apps/dev?id=6466686469831755521
