### ISSUE TITLE
Implement poster grid to app/ tvOS

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#389]
Currently poster grid is available in backend and web but not app/ tvOS. This is a valuable display type for kids app. 

tvOS only- display poster grid as poster

**Comment by fredrikved** [comment]
Implemented. Publishes in 4.0.6

**Comment by mulundapm** [comment]
When a show from poster grid is selected, the episode list under the player is empty. 4.5.0. This doesnt occur on other display type

https://github.com/bcc-code/bcc-media-platform/assets/88234679/b2937883-3583-4339-9ed9-680711b9434d

**Comment by mulundapm** [comment]
For poster grid, would want it so that
- If device is tablet, show poster grid as poster small
- If device is mobile, show poster grid as poster grid

**Comment by mulundapm** [comment]
@eliezerben @andreasgangso This will need to be prioritised
