### ISSUE TITLE
Missing npaw data in metabase

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#391]
Effective playtime, seek time, viewtime, completion rate, etc is missing in metabase if app anme is kids

**Comment by mulundapm** [comment]
https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzkyMSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw3MTA3NCxudWxsXSwia2lkcyJdXX0sInR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjo5fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319

**Comment by KillerX** [comment]
This is fixed both for the future and I think for the correct period in the past.
