### ISSUE TITLE
Investigate abnormal EBVS count from mobile and kids

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#414]
We are getting abnormal EBVS count from an user and the overall EBVS % has increased significantly since 21st May

https://metabase.bcc.media/question#eyJuYW1lIjoiQ291bnQiLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzkyMSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw3MTA3NCxudWxsXSwibW9iaWxlIl0sWyJiZXR3ZWVuIixbImZpZWxkIiw3MTA3MCx7InRlbXBvcmFsLXVuaXQiOiJtaW51dGUifV0sIjIwMjMtMDYtMDVUMTQ6MjY6MDArMDI6MDAiLCIyMDIzLTA2LTA1VDE2OjAyOjAwKzAyOjAwIl0sWyI9IixbImZpZWxkIiw3MTA1MSxudWxsXSwiUm9tYW5pYSJdXX0sInR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjo5fSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7Im1hcC50eXBlIjoicmVnaW9uIiwibWFwLnJlZ2lvbiI6IndvcmxkX2NvdW50cmllcyJ9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==

https://metabase.bcc.media/question#eyJuYW1lIjoiQ291bnQiLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzkyMSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw3MTA3NCxudWxsXSwibW9iaWxlIl0sWyJ0aW1lLWludGVydmFsIixbImZpZWxkIiw3MTA3MCxudWxsXSwtMzAsImRheSIseyJpbmNsdWRlX2N1cnJlbnQiOmZhbHNlfV0sWyI9IixbImZpZWxkIiw3MTA1NixudWxsXSwiWDdSVm13OEdLdFY3U1RndlUyWnNPZ3o3aGNUVCs1R3FIS1pjWkhxYmpMU2hZZWJNKytMV3cwcEpOZGRrNkFRRWV2UU9LSjRtZC80bkZFSk5zZjdUSEE9PSJdXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmllbGQiLDcxMDcwLHsidGVtcG9yYWwtdW5pdCI6ImRheSJ9XV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6OX0sImRpc3BsYXkiOiJsaW5lIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90IjpmYWxzZX0sIm9yaWdpbmFsX2NhcmRfaWQiOm51bGx9

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/b47f1b89-2f0b-4864-a256-11e4a214839f)

**Comment by andreasgangso** [comment]
Waiting for meeting with NPAW to help understand what EBVS really is, because it's higher than "Errors" and it's not that users are manually "exiting before video starts" because the only place we "stop" the player is via the X on the mini player.
