### ISSUE TITLE
Landing page of Bible Kids

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#417]
Acceptance criteria:

1. Buttons that direct users to appstore/ google playstore accordingly to download Bible Kids
2. Redirect users to appstore/ google playstore based on device type (when received as notification)

[Design](https://www.figma.com/file/4a7pCNPqS703RcBn4xPrL5/Bible-Kids-%E2%80%93-Mobile-App-MVP?type=design&node-id=9734-53247&t=0yqDBacuuIwViYHW-0)

**Comment by andreasgangso** [comment]
@mulundapm fyi this was a pretty good standalone task to give to kris so he's working on this

**Comment by andreasgangso** [comment]
https://github.com/starkris51/app-biblekids-io

**Comment by andreasgangso** [comment]
https://app.biblekids.io
https://github.com/bcc-code/app-biblekids-io

**Comment by mulundapm** [comment]
1. Should probably be boxed/centered on big screens
![MicrosoftTeams-image (8)](https://github.com/bcc-code/bcc-media-platform/assets/88234679/4892e8de-f426-4708-bbe7-1ab012a9d1dc)

2. When Bible Kids icon is clicked, link users to https://biblekids.io/

3. The download buttons are linking to BCC Media, it should be the Bible Kids app

**Comment by andreasgangso** [comment]
good now? @mulundapm

**Comment by mulundapm** [comment]
"Ser veldig bra ut. Gjerne link på logo på mobil også."- kjetil

**Comment by andreasgangso** [comment]
done
