### ISSUE TITLE
Indexing for episode number

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#420]
When episode number in title is enabled, only the following cases would the number show
- Episode list under player when user is playing in the context of show
- Title under the player where episode is being played in the context of show

Background:
Its confusing for users when the following case have indexing that is according to its episode number
![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/3f4e026f-a6fa-421c-a2de-a8ba11f2dfb6)
![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/e2482ada-db9a-4065-b311-c2c2da24759d)
When a specific episode is added as a feature banner, indexing is also not necessary

**Comment by fredrikved** [comment]
Should I make Episode.number nullable and just set it null if it's not supposed to be visible @andreasgangso ?

**Comment by andreasgangso** [comment]
@fredrikved don't you already have dynamic titles, so this is just about adding another condition?
also @mulundapm aren't we doing some similar "title modification" with production dates?

**Comment by fredrikved** [comment]
But determining when the title has a number and when it shouldn't isn't very easy from my side when it's page-based.

**Comment by andreasgangso** [comment]
Me and fredrik talked and concluded on adding an extra checkbox on admin for collections: show episode number in title.

So you now have 2 places to configure this:
- Show level: Episodes shown in the context of a show (e.g. on episode page)
- Collection level: Episodes viewed in the context of a collection (e.g in a section or episode page navigated via section).

It's a tradeoff which creates a little bit more admin work, but it simplifies the backend logic a lot and gives a bit more flexibility (you can have episode numbers even though the show default is to not have that).

**Comment by mulundapm** [comment]
It was a thing, still am but the definition is not defined yet since we have various cases. Can work on defining it this week.

**Comment by fredrikved** [comment]
Season and collection yes.

**Comment by andreasgangso** [comment]
@fredrikved "to be tested" 👍
