### ISSUE TITLE
tvOS- Context doesnt apply after autoplay next

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#422]
Repro:

1. Open video within a context
2. Play video within the context
3. Wait until video play next
4. Second video start playing
5. Quit player
6. User lands on episode page within its show instead of context

verj 4.0.8

**Comment by fredrikved** [comment]
Guessing this is the version on testflight? Live is a bit outdated.

**Comment by mulundapm** [comment]
It should not open a new page when video is auto played next. e.g. after queueing/ auto playing an entire series, user would end up with a lot of open pages. Had to click back multiple times to navigate back to home page

**Comment by mulundapm** [comment]
yes, 4.0.8

**Comment by fredrikved** [comment]
Done. Will be fixed in next build of 4.0.8
