### ISSUE TITLE
Error when creating episode under show n directus

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#439]
@fredrikved Can you update the task with details on what we've talked about? That fixing an episode error doesnt work if episode is created under a show?

**Comment by fredrikved** [comment]
We didn't get to reproduce the actual error though or?

I only know of the UX challenges, not of errors.

**Comment by mulundapm** [comment]
Repro:
1. Select a show
2. Open season and create an episode
3. Add metadata of episode but leave out fields like publish date or production date
4. Click confirm on episode, season and show level
5. Get error message on publish date and production date that it is required
6. Navigate back to the episode and add the missing field
7. Confirm on episode, season and show level
8. Get the same error message
9. Navigate back to the episode and the previous filled info are gone

**Comment by mulundapm** [comment]
You can update the task description to address this

**Comment by fredrikved** [comment]
Should be fixed.
