### ISSUE TITLE
Testing environment for Bible Kids

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#440]
As admin for Bible Kids, I want to test new features/ display on app without it being public to users.

**Comment by andreasgangso** [comment]
We also already have the "env override" in developer options so you can use dev.admin.brunstad.tv
But I realize that's cumbersome.

@fredrikved to get different content for public users, can we add a feature where we can send a "x-usergroups" header and the request gets those usergroups? with a whitelist ofc.
e.g. "betatesters".

**Comment by fredrikved** [comment]
How would we know what to whitelist?

**Comment by fredrikved** [comment]
Backend implementation is done. 

Include header `x-explicit-roles` with comma-separated codes of explicitly available usergroups to use them.
