### ISSUE TITLE
Shutdown old.brunstad.tv

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-platform#456]
- [x] #455 
- [x] Shut down the "azure cloud service" (old import service)
- [x] Remove forward on `/series`
- [x] Remove sync from new
- [x] Remove dns
- [x] Cloud Run disable/scale to 0 and make private so we can be sure no reqs can work
- [x] Dump backup of old DB
- [x] Shut down old DB 
- [x] Decide what to do with AndroidTV

**Comment by andreasgangso** [comment]
> * [ ]  Remove forward on `/series`

not sure what you mean. https://brunstad.tv/series/x should keep working to ensure old links keep working

**Comment by fredrikved** [comment]
> not sure what you mean. https://brunstad.tv/series/x should keep working to ensure old links keep working

At the moment GET requests to this url is sent to the old API due to old player implementations.

**Comment by KillerX** [comment]
Note: DB has been scaled down

**Comment by KillerX** [comment]
Note: Cloud RUN services are now scaling to 0
