### ISSUE TITLE
Missing user ID on bcc media platfroms

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#468]
Jeg har konto for å komme inn på portalen den fungerer. Men det fungerer ikke når jeg skal logge inn på bcc media appen.

https://projects.bcc.no/desk/tickets/10516540/messages

**Comment by andreasgangso** [comment]
Var veldig lite info her så jeg sendte en follow up.
Jeg tipper dette løses via vanlig support, trenger ikke en issue i github foreløpig.

Han bare sliter med å logge inn av en eller annen grunn.
At user ID er null betyr bare at han sendte via public "contact us" 👍
