### ISSUE TITLE
Fix livestream DNS

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#469]
For live.stream.brunstad.tv
- The DNS doesnt seem to be managed by terraform, it seems to be managed directly in the azure portal.
- It currently goes through azure traffic manager "btvstream" because we previously did some rerouting to Ivans servers instead of cloudfront for certain african regions. But Ivan told me recently to disable the last one (tanzania) so currently the traffic manager is useless.

1. Move to terraform
2. Point directly to cloudfront
3. Ensure everything still works well (and follow up on certificate renewal that nothing is broken)

**Comment by mulundapm** [comment]
What benefit does this bring?  And any risk if its not done?

**Comment by KillerX** [comment]
Risks of not doing: 
* Extra costs and complexity
* It's not in the "standard" systems so can be easily broken
* Could stop working because we forget something
