### ISSUE TITLE
Only audio starts playing when autoplay next happened through seasons

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#471]
Repro:
1. Select the last episode of a season
2. Play video in player page
3. Autoplay next episode (First episode of next season)
4. Audio starts playing but image doesnt. 

verj 3.5.8+ 2300078

https://github.com/bcc-code/bcc-media-platform/assets/88234679/0a90630b-5585-481d-af36-7b3b208adc72

**Comment by andreasgangso** [comment]
I can't reproduce this using the repro steps even on v4.5.8, not on android nor on iOS.
I tried with magazine and bible explorers because sara&simon no longer has two seasons.
Maybe it was something very specific to this episode, was it unlisted or something special about it?

**Comment by andreasgangso** [comment]
I tried with both the native player and the flutter player, btw.

**Comment by mulundapm** [comment]
I cant reproduce it now neither. It was published as usual, so shouldn't be any special about it. Odd..
