### ISSUE TITLE
Unable to export sequence of ANIM_ to VOD

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#479]
No complete status on channel

- [x] ANIM_S01_E01_SEQ // VX-457732
- [x] ANIM_S01_E02_SEQ // VX-457733
- [x] ANIM_S01_E03_SEQ // VX-457734
- [x] ANIM_S01_E05_SEQ // VX-457736
- [x] ANIM_S01_E06_SEQ // VX-457737
- [x] ANIM_S01_E08_SEQ // VX-457739

**Comment by KillerX** [comment]
The problem is that the VIDEO Encode fails to start for some reason. Looking into what the background reason for this is.

**Comment by KillerX** [comment]
Seems like the underlying problem is that the original files are on "space" disk. Not sure where this fails but moving them (a good idea anyways) seems to fix the issue.

**Comment by KillerX** [comment]
Everything should be available as Assets in Admin
