### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#481]
- [x] Bible Kids app in setting page
- [x] BCC Media app in setting page
- [x] BCC Media web (next to privacy policy at footer)
- [x] tvOS below about us in setting
https://bcc.media/en/terms-of-use/

**Comment by andreasgangso** [comment]
Shouldnt bible kids have its own biblekids.io link?

**Comment by andreasgangso** [comment]
Done in https://[github.com/bcc-code/bcc-media-app/commit/ff4d1931e1f1ccdda9bad7d4a609b1fbf6a30461](https://github.com/bcc-code/bcc-media-app/commit/ff4d1931e1f1ccdda9bad7d4a609b1fbf6a30461)

So it will be released in v4.6.6
