### ISSUE TITLE
Downlandable in bccm web

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#502]
As user with bad internet connect (have to be approved by redaksjon), I want to be able to download meetings from web so that i dont have to rely on internet connection for our local church to follow along the meeting, 
As admin, I want certain meetings to only be downloadable on web for certain users.

(Everything should be downloadable on mobile for bcc members, but on web, only a certain content should be downloadable for certain group)

**Comment by fredrikved** [comment]
I think this should be implemented already.

Just create a role {role}
- assign the specified emails

Add another one: bccm-web-{role}
- add this to the "downloadables" section on the specified episodes.

Feel free to reopen if this doesn't work as expected.
