### ISSUE TITLE
Mismatch translation in crowdin

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#517]
Seems like a change that was done 13 days has messed up the translation strings for all languages.

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/179fec4f-76be-4d2c-bb1f-306ef98bb5fc)
![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/0041dbe2-ecb2-4233-8a84-981d1170f70b)

Er det noen som skjer i crowdin? Alle tekster ser ut til å vaere blandet? (Rød=orig Blå=overset, dette er proofread skjermen) eller er det bare meg?

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/512bac48-b56e-4c8f-b0a9-3100f62eaea7)

**Comment by mulundapm** [comment]
@fredrikved Seems like majority of translation under the status "Hidden" are a mess. Can you verify if these strings are used anywhere? If theyre not being used, could we have them removed? since they are messing the translation memory as well.

**Comment by fredrikved** [comment]
This was a serious bug, but it's fixed now. I haven't unhidden the hidden strings (hidden because of this bug), but they will appear once there's an update or something.
