### ISSUE TITLE
Samtalekort websiden

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#523]
Confirmed with Randi, and she is ok with having image if that is simpler to prepare. UX is compromised but she mentioned its acceptable since the scanning is only meant for mentors. Team ungdom doesnt want mentee to be on phone at all.

I would consider everything else as edge cases therefore dont think its worth the effort to make the questions web based.

**Comment by KillerX** [comment]
Archived at https://github.com/bcc-code/bccm-issues/tree/main/samtalekort 
Deployed manually to the S3 static bucket with a redirect from https://bcc.media/forbilde
