### ISSUE TITLE
Voting webapp for høstcamp

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#567]
Acceptance criteria:
- [ ] Webapp for voting (without inlogging)
- [ ] translation

Definition of done:
Tested and approved by team ungdom

**Comment by KillerX** [comment]
Note, this should be used as the backend: https://github.com/bcc-code/bcc-media-utils/tree/main/counter

It can handle basically anything you throw at it with a small VM.

**Comment by KillerX** [comment]
Details after meeting with Fredrik Floor:

1 Question
4 Answers
Results in "admin" no need for nice presentations, will be copied to PP
Can be open all the time, needs a reset button.

**Comment by KillerX** [comment]
Status: 

- [ ] Webpage implemented and approved by Fedrik Floor
- [ ] Translations ready for translators
- [ ] Translations Imported
- [ ] Redirect on re-visit
  - Ready tested, but disabled in code
- [ ] Submit data to server
  - Ready, tested locally. Needs correct server IP/DNS
- [ ] Counter server
  - Software ready, needs to be deployed to a VM (< 1h work)
