### ISSUE TITLE
Terms and condition on VOD download on web

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#598]
When user click download button, show a pop up check box asking user to agree with the terms before proceeding. 

dod: tested by Kjetil and Tove on biblekids.io and bccm web

**Comment by mulundapm** [comment]
@fredrikved Need to replace the links with these
Terms of use: https://bcc.media/en/terms-of-use/
Provacy policy: https://bcc.media/no/personvern/

**Comment by fredrikved** [comment]
Fixed
