### ISSUE TITLE
Empty "episode.next" in api

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#603]
episode.next is empty if the episode is the last in the series or something.
Not sure the exact reproduction steps, but see examples below.

```graphql
query KidsGetNextEpisodes($episodeId: ID!, $context: EpisodeContext) {
  episode(id: $episodeId, context: $context) {
    next(limit: 30) {
      id
      title
      cursor
    }
  }
}
```

## Example 1

Happens every time on this episode.
**Note**: the cursor can be null and it still happens. shuffle true/false also does not affect it.

```json
{
    "episodeId": "858",
    "context": {
        "shuffle": false,
        "cursor": "eyJrZXlzIjpbNzY5LDc3OSw3ODIsNzg2LDgzNCw4NTMsODM4LDg1Nyw4NThdLCJjdXJyZW50SW5kZXgiOjh9"
    }
}
```

## Example 2

Happens with shuffle on this episode if you spam it enough without a cursor. Every 4-5 time for me.

```json
{
    "episodeId": "838",
    "context": {
        "shuffle": true
    }
}
```

**Comment by fredrikved** [comment]
Fixed in the other "linked" issue. The order in the queue didn't start from the initial episode, and if it was the last episode in the show, and no linked collection (on show), it would just stop there.
