### ISSUE TITLE
Kids: Episode suggestions beneath player

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#618]
Acceptance criteria:
Always show at least 10 episodes
- When play random is clicked, randomly select 10 episodes to be shown as suggestions
- When item is clicked, show next episode in show+ random episodes until at least 10 items are shown

**Comment by mulundapm** [comment]
@andreasgangso app can add into open beta after this is done

**Comment by andreasgangso** [comment]
@fredrikved all the "random episodes" is now from the same show. its a bit weird and I think what we really want is for it to be completely random selection of **any** of the available episodes in the entire app? @mulundapm

**Comment by fredrikved** [comment]
Make a collection and add it as the related collection on show.

**Comment by andreasgangso** [comment]
So the best would probably be to have a tag on all the kids content and create a collection from it and set it on all the episodes.
Sounds a bit cumbersome but it also makes it easier cross-app e.g. if we have something similar on bcc media

**Comment by andreasgangso** [comment]
actually, is it nullable? i see you use tags as a fallback so maybe its better to just use that logic instead of setting related

**Comment by fredrikved** [comment]
Yes, tags are there as well, but they aren't used for most kids videos...
