### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#638]
Migrating from algolia to elastic

- [ ] first version of querying ES from GO
- [ ] send data to elasticsearch
- [ ] build elastic search index
- [ ] Feature flag

**Comment by andreasgangso** [comment]
started briefly on tihs

**Comment by kkuepper** [comment]
nice. Can you create a draft PR so I can follow the progress?

**Comment by andreasgangso** [comment]
> nice. Can you create a draft PR so I can follow the progress?

https://github.com/bcc-code/bcc-media-platform/compare/feat/elasticsearch

**Comment by andreasgangso** [comment]
@fredrikvedvik aka mr elastic, do you have any tips for implementation?

**Comment by andreasgangso** [comment]
or lmk if you just want to do it 😏

**Comment by kkuepper** [comment]
from my point of view, you don't need to implement everything. I just need a good starting point. That means a way to get the data into elastic search and a way to run integration tests against elastic search. The actual search indexes, I can build myself.
In the [BMM API you can see an example](https://github.com/bcc-code/bmm-api/blob/develop/BMM.Api.Infrastructure.Tests/ElasticSearch/SearchTrackTests.cs) on what the tests could look like.

**Comment by mulundapm** [comment]
Next: extend the capability of elastic search + phrase roll out

**Comment by KillerX** [comment]
The flag is `elastic-search-enabled`.

All active backend flags are defined in https://github.com/bcc-code/bcc-media-platform/blob/master/backend/unleash/flags.go if you need to find/check the other ones.

**Comment by mulundapm** [comment]
For search terms like 

- Da jeg var barn
- kampen
- Det store

Where terms are from the title of a show,
There is no result relevant result (results from the serie) both on show and episode level

**Comment by mulundapm** [comment]
Created #1043 to address search quality
