### ISSUE TITLE
Move apps to new Apple store account

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-platform#665]
Need to validate what to do with testers, certs, etc

**Comment by andreasgangso** [comment]
https://developer.apple.com/help/app-store-connect/transfer-an-app/overview-of-app-transfer/
https://developer.apple.com/help/app-store-connect/transfer-an-app/app-transfer-criteria

I've read through these two apple docs on this, and here's the only things I've found that is relevant for us.

### Testflight
from https://developer.apple.com/help/app-store-connect/transfer-an-app/app-transfer-criteria
> TestFlight beta testing should be turned off for all beta versions of the app. You must remove all builds and testers from the app you want transferred and clear each information field below Test Information for every localization.

So we need to remove them all and send out new test links.

### Push notifications
The docs says:

> Associated client SSL certificates, [TLS certificates](https://developer.apple.com/help/account/configure-app-capabilities/communicate-with-apns-using-a-tls-certificate/), and [authentication tokens](https://developer.apple.com/help/account/configure-app-capabilities/communicate-with-apns-using-authentication-tokens) for push notifications aren’t transferred. If the app uses Apple Push Notifications service (APNs), the recipient needs to create a client SSL certificate using the recipient’s developer account to reenable it.

But this is a server-side thing so we just need to remember to update the token in firebase (project settings -> cloud messaging -> ios). [This thread message](https://developer.apple.com/forums/thread/4799?answerId=198829022#198829022) confirms that push should still work for previous versions of the app if you update the certificate/token.

### "Sign in with apple"

BCCs auth0 "sign in with apple" is linked to our team ID (KJ6LCYQ3A8), so the "apple" connection in auth0 will be affected by this. Im not sure exactly in what way. Its all a bit complicated and confusing how this works: https://developer.apple.com/documentation/sign_in_with_apple/transferring_your_apps_and_users_to_another_team

But we should warn the members team and just go ahead, imo. We have 60 days to figure out how it works and "migrate the users".

Here's the "key" thats being used by auth0: https://developer.apple.com/account/resources/authkeys/review/L86YN4GFZT
An auth0 forum post on transferring: https://community.auth0.com/t/change-sign-in-with-apple-client-id-and-retain-user-accounts/99423/2

**Comment by KillerX** [comment]
After all our stuff is migrated out we transfer the account to Fellestjenester. They can maintain the key for "Sign in with apple" etc.

**Comment by KillerX** [comment]
@mulundapm this is ready from my side waiting for green light from you. "Locks" up the apps for up to 48h. (No updates, no testing, no releases).

**Comment by KillerX** [comment]
Kids done
Prepping Media and BMM

**Comment by mulundapm** [comment]
Missing BMM

**Comment by KillerX** [comment]
Pick this up again Jan. 10.

**Comment by KillerX** [comment]
Cake? XD
