### ISSUE TITLE
Bible project- questions and answers webview

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#669]
Feature:
- Inlogging required but should be auto logged in (verify with Randi)
- A page to display a list of Q&A divided in weekly basis
- Translation
- Collection and export of questions with date and age

Dod: verified with team ungdom

**Comment by mulundapm** [comment]
inlogging is needed

**Comment by andreasgangso** [comment]
Has new secret url

**Comment by andreasgangso** [comment]
Repo is https://github.com/bcc-code/study-qa
