### ISSUE TITLE
A/B test on auto play for kids

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#694]
Play next episode within the series
Play next preview/ countdown
Put it behind unleash
Sticky to device ID (determine what this should be)
Method to identify which playback is an autoplay on metabase

**Comment by sifferhans** [comment]
- [ ] Cancel autoplay if the user interacts with the page
- [ ] Analytics: log when autoplay and when cancelling autoplay

**Comment by sifferhans** [comment]
@mulundapm How should this be linked to npaw data?

**Comment by sifferhans** [comment]
@mulundapm We can use the `Session ID` to link the `did-autoplay-next` and npaw events

**Comment by sifferhans** [comment]
This can be tested in the newest version on TestFlight.
1. Should autoplay next episode if the user doesn't touch the screen.
2. Autoplay should be cancelled if the user interacts with the screen
