### ISSUE TITLE
Direct users from BCCM Live to Connect

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#722]
Direct users to connect app if exist, if not to app store

**Comment by andreasgangso** [comment]
I'm releasing the following feature flags in v5.1.2.
The button only opens the store for now, as we have no identifiers to work with. (it deep links to search "bcc live" on android)

## Feature flag: link-to-bcc-live
![Image](https://github.com/bcc-code/bcc-media-platform/assets/727125/b83ccac4-d6d4-44f2-9296-e99e8f0e0701)

## Feature flag: force-bcc-live
![Image](https://github.com/bcc-code/bcc-media-platform/assets/727125/b03e5b64-9866-4fb9-8bfc-0ba44c325b20)

**Comment by andreasgangso** [comment]
@fredrikved can you implement something like this for tvos?
