### ISSUE TITLE
Fix async for julekonsert del 2

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#727]
https://mediabanken.brunstad.tv/item/VX-473940/?index=41&search_id=176852&parentPage=search

Both embedded and reaper audio are slightly asynced. This is taken from channel in youplay.

**Comment by KillerX** [comment]
All languages should now be correct to a reasonable degree.

**Comment by mulundapm** [comment]
Is it published? Where could I find the updated audio tracks?

**Comment by KillerX** [comment]
They are updated in MB

**Comment by KillerX** [comment]
The files were replaced directly.
