### ISSUE TITLE
Africa stream certificate

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#791]
Domain
certificate

**Comment by KillerX** [comment]
2024/02/05 15:09:33 [INFO] [vod.brunstad.tv, vod.stream.brunstad.tv, vod2.stream.brunstad.tv, live.stream.brunstad.tv, liveoht.brunstad.tv] acme: Validations succeeded; requesting certificates
2024/02/05 15:09:34 [INFO] [vod.brunstad.tv] Server responded with a certificate.
