### ISSUE TITLE
Unable to cast some of VOD

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#821]
E.g. https://app.bcc.media/episode/11 
"The videos for Det Store Sjoslaget don't start on my chromecast. I get a 1 second loading screen and then back to the BCC Media logo."

Device | AC2003 | Environment overschrijven | null | Fabrikant | OnePlus | Operating System | Android 12 | Scherm afmetingen | 2400x1080 | App versie | 5.1.2+2300112
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

https://projects.bcc.no/desk/tickets/10563040/messages
https://projects.bcc.no/desk/tickets/10550780/messages

**Comment by mulundapm** [comment]
This is still the case when casting episode 1 of det store sjoslaget. 

https://github.com/bcc-code/bcc-media-platform/assets/88234679/e0babf6a-6f8b-4b40-8590-ff0110903f4a

**Comment by fredrikved** [comment]
It's an azure asset. Can you reexport the affected episodes manually?

Might have to fix the resolutions manually as well, as we don't support the resolution on at least some of them.

**Comment by fredrikved** [comment]
@KillerX might have some insight, but it can also be done in final cut or something like that.

ffmpeg can probably do it, but I didn't figure it out straight away (haven't asked ai yet though).
