### ISSUE TITLE
VOD playback speed selection on tvOS

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#838]
Currently there is playback speed selection on mobile, will need the same be implemented on tvOS and web

Options
- 0.75x
- 1.0x
- 1.5x
- 1.75x
- 2.0x

**Comment by mulundapm** [comment]
There is no audio when the playback speed other than 1.0x is selected

**Comment by sifferhans** [comment]
@mulundapm Does the issue appear on both web and tvOS, or only tvOS?
