### ISSUE TITLE
Fix caching for bccm web

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#842]
Seems like we are occasionally serving old versions of stuff.
We have `Cache-Control: max-age=60`

I've seen websites embedded in the app jump from old version -> new version -> old version. Which could mean that both the browser cache and the cdn is serving old versions (the second time).

I think the issue right now is that both the cdn and the browsers are allowed to use a `stale` (>60 second old) response. 
We could probably solve this by putting `cache-control: max-age=60, must-revalidate`, as `must-revalidate` prevents browsers and cdns from using stale responses.

**Comment by fredrikved** [comment]
Updated the cache header on index.html
