### ISSUE TITLE
"Label" on short view are empty for new shorts from 8. feb onward

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#843]
https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjQwMjMsIm9yZGVyLWJ5IjpbWyJkZXNjIixbImZpZWxkIiw3NTM5NCxudWxsXV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1uX3dpZHRocyI6W251bGwsbnVsbCxudWxsLDM2OF19fQ==

**Comment by KillerX** [comment]
Fixed. Some are still in BQ but the data is deleted in admin so no way to show the titles.
