### ISSUE TITLE
Quote of the day

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#848]
- [x] Section in app that display quote
- [x] Same quote for all users, 1 new quote everyday
- [x] Share function
- [x] Statistic of share
- [x] mark as read
- [x] collecting feedback (to open a link)
- [x] A feedback to show users have read todays quote
- [x] Translation

**Comment by mulundapm** [comment]
https://brunstadchristianchurch-my.sharepoint.com/:x:/g/personal/priscilla_mulunda_bcc_no/EXV3z4A9O-RPgn6dRfQEN0IB6BaHPV2EWZuETe0TyQmyjQ?e=yPTt0y

Quotes with publishing schedule

**Comment by andreasgangso** [comment]
The feedback url is controlled by `/r/quotes-feedback` in admin

**Comment by mulundapm** [comment]
after marking as read, the share button doesnt appear for android

**Comment by andreasgangso** [comment]
> after marking as read, the share button doesnt appear for android

Yes. Wasn't possible via the webview natively on android. But the newest version supports this. If supported, the share button shows.
