### ISSUE TITLE
Automated test for analytics

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#863]
Need a process for ensuring set up for RS/ npaw data are correct per release

prototype

**Comment by andreasgangso** [comment]
I made this for RS and its working in prod.
Npaw is a different beast and i dont think its worth it.

**Comment by andreasgangso** [comment]
Changing story points to 1 and splitting out tvos

**Comment by andreasgangso** [comment]
Jeg satte opp en webhook i rudderstack som piper dataen i prod også til https://github.com/bcc-code/analytics-test-webhook (hosted in the utils google project, deployed manually with `gcloud run deploy`).
 
(men en rudderstack transformer whitelister kun eventer hvor userId == automated test kontoen) 
 
Også sjekker vi bare om vi har fått litt data inn: https://github.com/bcc-code/bcc-media-app/blob/master/scripts/check_analytics.sh
