### ISSUE TITLE
Fix age groups and country disappearing by caching the user profile

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#890]
Auth0 id tokens has a limitation where custom claims can't be injected upon refresh.
We need e.g. age group for analytics but that data disappears upon refreshing the id token.

We can work around this by storing the claims manually instead of reading the idtoken.

bcc media, kids, live
- [x] bccm flutter

**Comment by mulundapm** [comment]
Looking at RS screens event, theres a significant decrease in empty age group under "context traits age group"
https://metabase.bcc.media/question#eyJuYW1lIjoiRGlzdGluY3QgdmFsdWVzIG9mIFVzZXIgSUQiLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMzNjIsImFnZ3JlZ2F0aW9uIjpbWyJkaXN0aW5jdCIsWyJmaWVsZCIsNjE1MTEseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiw2MTA3OSx7InRlbXBvcmFsLXVuaXQiOiJ3ZWVrIiwiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dXSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw2MTEwMCxudWxsXSwiQkNDIE1lZGlhIl0sWyJiZXR3ZWVuIixbImZpZWxkIiw2MTA3OSx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiIsInRlbXBvcmFsLXVuaXQiOiJkYXkifV0sIjIwMjMtMTAtMDdUMDA6MDA6MDArMDI6MDAiLCIyMDI0LTA3LTEwVDAwOjAwOjAwKzAyOjAwIl0sWyI9IixbImZpZWxkIiw2MTA4NSxudWxsXSwiNS40LjAiLCI1LjQuMSIsIjUuNC4zIiwiNS40LjQiLCI1LjQuNSIsIjUuNC42IiwiNS40LjciLCI1LjQuOCIsIjUuNC45IiwiNS4zLjAiLCI1LjMuMSIsIjUuMy4yIiwiNS4zLjMiLCI1LjMuNCIsIjUuMy41IiwiNS4zLjYiLCI1LjMuOCIsIjUuMy45Il0sWyJpcy1lbXB0eSIsWyJmaWVsZCIsNjE1MDUsbnVsbF1dXX19LCJkaXNwbGF5IjoiYmFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsidGltZXN0YW1wIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXSwiZ3JhcGguc2VyaWVzX29yZGVyX2RpbWVuc2lvbiI6bnVsbCwiZ3JhcGguc2VyaWVzX29yZGVyIjpudWxsfSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=
