### ISSUE TITLE
Chapter import: ingest to bcc-media-platform

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#900]
Subclips -> Timedmetadata

- [ ] Metadata
- [ ] Image (10s in)
- [ ] Update existing assets

Before exporting, would want the following mapping of data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/priscilla/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/priscilla/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Directus   chapter | Mediabanken chapters
-- | --
Song | sang
  | musikkvideo
Sing along | singalong
Speech | tale
  | vitnesbyrd
  | appelle
Interview | panel
  | intervju
Temafilm | kortfilm
  | anslag
  | temafilm
Others | rest of the types

</body>

</html>

**Comment by andreasgangso** [comment]
- [ ] Chapter import: ingest to bcc-media-platform
- [ ] Chapter import: send to bcc-media-platform
