### ISSUE TITLE
Expose content type for contributions

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#931]
- [x] Rename "chapter type" to "content type"
- [x] Replace content type in mediaitems to use the same enum as chapters: panel, theme, speech, etc.
- [x] Expose filtering by content type in graphql for contributions
- [x] Expose contribution content types on the person to enable the pills (maybe better as part of the pagination object as facets basically)

Update both code and directus

**Comment by KillerX** [comment]
Fixed in #942
