### ISSUE TITLE
Negative chapter times

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-platform#975]
This asset: https://admin.brunstad.tv/admin/content/assets/2798 has chapters outside of its range.
Something is wrong with the export of the timedmetadata

**Comment by andreasgangso** [comment]
This mine to test

**Comment by mulundapm** [comment]
I have reexported this and it doesnt seem to be an issue 

https://admin.brunstad.tv/admin/content/assets/6852

**Comment by andreasgangso** [comment]
I deleted the old timedmetadata and did a timedmetadata export.
https://admin.brunstad.tv/admin/content/assets/2798
The timedmetadata does not get exported.
Should change the code to delete automatically. but not a big deal.
