### ISSUE TITLE
Prevent requiring users to re-login upon an app update

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#986]
https://metabase.bcc.media/question/724-logins

Login count for the last 2 months has increased significantly, need to be investigated and reduce the count

- setup tenant with faster refresh times
- try to reproduce it
- otherwise add logging

**Comment by andreasgangso** [comment]
Sent support ticket to auth0

**Comment by andreasgangso** [comment]
fixd

**Comment by andreasgangso** [comment]
still waiting

**Comment by sifferhans** [comment]
We've got an answer from Auth0. They told us to try turning off the "Revoke refresh token" flag in the tenant settings.

**Comment by sifferhans** [comment]
Reng disabled the mentioned flag in the tenant settings

**Comment by mulundapm** [comment]
This issue is still persisting with 90 visits to login page per day. Will have to do further investigation on this for other alternatives. 

![Image](https://github.com/user-attachments/assets/343f39e4-b14b-42c0-9a0f-3dbcbf3d4171)

**Comment by sifferhans** [comment]
@andreasgangso Should we wait some days before doing anything more here?

**Comment by sifferhans** [comment]
I am adding some metadata to the login screen analytics to see how many of the users hitting the login page has ever logged in.
This might help us see if the large amounts of login page views are from public users or BCC members.

https://github.com/bcc-code/bcc-media-app/pull/424
https://github.com/bcc-code/bccm-flutter/pull/2

**Comment by sifferhans** [comment]
We'll wait for some more data before doing anything more here

**Comment by mulundapm** [comment]
.26 was released for android 3.sept and is currently in review for iOS

**Comment by sifferhans** [comment]
@mulundapm The app was rejected for iOS
https://appstoreconnect.apple.com/apps/913268220/distribution/reviewsubmissions/details/42966992-97a6-4c15-a5cd-1df70cfa33c7

**Comment by mulundapm** [comment]
https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMzNjIsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwib3JkZXItYnkiOltbImRlc2MiLFsiYWdncmVnYXRpb24iLDBdXV0sImJyZWFrb3V0IjpbWyJmaWVsZCIsNjEwNzkseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoiLCJ0ZW1wb3JhbC11bml0IjoiZGF5In1dLFsiZmllbGQiLDc2NzQ4LHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIn1dXSwiZmlsdGVyIjpbImFuZCIsWyJ0aW1lLWludGVydmFsIixbImZpZWxkIiw2MTA3OSxudWxsXSwtOTAsImRheSIseyJpbmNsdWRlLWN1cnJlbnQiOmZhbHNlfV0sWyI9IixbImZpZWxkIiw2MTA5MCxudWxsXSwibG9naW4iLCJ0di1sb2dpbiJdLFsiPSIsWyJmaWVsZCIsNjEwNjIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIkFuZHJvaWQiXSxbIj0iLFsiZmllbGQiLDYxMDg1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCI1LjYuMjYiXV19fSwiZGlzcGxheSI6ImxpbmUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90IjpmYWxzZSwiZ3JhcGguZGltZW5zaW9ucyI6WyJ0aW1lc3RhbXAiLCJjb250ZXh0X2FwcF9uYW1lIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXX0sIm9yaWdpbmFsX2NhcmRfaWQiOjcyNH0=

Majority of the "has ever logged in" event are empty for users with app version .26 on android

**Comment by sifferhans** [comment]
added more verbose logging for auth, so we can see what triggers logouts

**Comment by sifferhans** [comment]
> The app was rejected for iOS https://appstoreconnect.apple.com/apps/913268220/distribution/reviewsubmissions/details/42966992-97a6-4c15-a5cd-1df70cfa33c7

I've replied to the review. Andreas has gone through this exact issue before.
